#!/usr/bin/env php
<?php


if (!function_exists('ast\\parse_code')) {
  echo "[!] The php extension ast (github.com/nikic/php-ast) is required!" . PHP_EOL;
  exit(1);
}

require_once 'vendor/autoload.php';


if ($argv && $argv[0] && realpath($argv[0]) === __FILE__) {
  $check_script = $argv[1] ?? '';
  
  if (!file_exists($check_script)) {
    echo "[!] That file does not exist $check_script" . PHP_EOL;
    exit(2);
  }
  
  $detectors = Detectors\getDetectors();

  if (!is_dir($check_script)) {
    Detectors\investigateFile($check_script, $detectors);
  } else {
    $files =  rsearch(realpath($argv[1]), ".php");
    foreach ($files as $file) {
      Detectors\investigateFile($file->getPathname(), $detectors);
      echo $file->getPathname() . PHP_EOL;

      $matches = array_filter($detectors, function($detector) {
        return !$detector->shouldInvestigate();
      });

      if (count($matches) === count($detectors)) {
        break;
      }
    }
  }

  $notes = [];
  foreach($detectors as $detector) {
    $notes = array_merge($notes, $detector->getNotes());
  }

  Detectors\Printers\printCli($notes);

}
