<?php

$version = 55;

return new  Detectors\DetectVersionSet($version, [
  new Detectors\DetectByFeature($version, 
    function ($node) {
      return ($node->kind === ast\AST_YIELD || $node->kind === ast\AST_YIELD_FROM);
    }, 
    'Keyword yield'
  ),
  new Detectors\DetectByFunction($version, [
    'array_column',
    'boolval',
    'json_last_error_msg',
    'password_get_info',
    'password_hash',
    'password_needs_rehash',
    'password_verify',
    'hash_pbkdf2',
    'openssl_pbkdf2',
    'curl_escape',
    'curl_file_create',
    'curl_multi_setopt',
    'curl_multi_strerror',
    'curl_pause',
    'curl_reset',
    'curl_share_close',
    'curl_share_init',
    'curl_share_setopt',
    'curl_strerror',
    'curl_unescape',
    'imageaffinematrixconcat',
    'imageaffinematrixget',
    'imagecrop',
    'imagecropauto',
    'imageflip',
    'imagepalettetotruecolor',
    'imagescale',
    'mysqli_begin_transaction',
    'mysqli_release_savepoint',
    'mysqli_savepoint',
    'pg_escape_literal',
    'pg_escape_identifier',
    'socket_sendmsg',
    'socket_recvmsg',
    'socket_cmsg_space',
    'cli_get_process_title',
    'cli_set_process_title',
    'datefmt_format_object',
    'datefmt_get_calendar_object',
    'datefmt_get_timezone',
    'datefmt_set_timezone',
    'datefmt_get_calendar_object',
    'intlcal_get_error_code',
    'intlcal_get_error_message',
    'intltz_get_error_code',
    'intltz_get_error_message',
  ]),
  new Detectors\DetectByConst($version, [
    'IMG_AFFINE_TRANSLATE',
    'IMG_AFFINE_SCALE',
    'IMG_AFFINE_ROTATE',
    'IMG_AFFINE_SHEAR_HORIZONTAL',
    'IMG_AFFINE_SHEAR_VERTICAL',
    'IMG_CROP_DEFAULT',
    'IMG_CROP_TRANSPARENT',
    'IMG_CROP_BLACK',
    'IMG_CROP_WHITE',
    'IMG_CROP_SIDES',
    'IMG_FLIP_BOTH',
    'IMG_FLIP_HORIZONTAL',
    'IMG_FLIP_VERTICAL',
    'IMG_BELL',
    'IMG_BESSEL',
    'IMG_BICUBIC',
    'IMG_BICUBIC_FIXED',
    'IMG_BLACKMAN',
    'IMG_BOX',
    'IMG_BSPLINE',
    'IMG_CATMULLROM',
    'IMG_GAUSSIAN',
    'IMG_GENERALIZED_CUBIC',
    'IMG_HERMITE',
    'IMG_HAMMING',
    'IMG_HANNING',
    'IMG_MITCHELL',
    'IMG_POWER',
    'IMG_QUADRATIC',
    'IMG_SINC',
    'IMG_NEAREST_NEIGHBOUR',
    'IMG_WEIGHTED4',
    'IMG_TRIANGLE',
    'JSON_ERROR_RECURSION',
    'JSON_ERROR_INF_OR_NAN',
    'JSON_ERROR_UNSUPPORTED_TYPE',
  ]),
  new Detectors\DetectByClass($version, [
    'CURLFile',
    'DateTimeImmutable',
    'DateTimeInterface',
    'IntlCalendar',
    'IntlGregorianCalendar',
    'IntlTimeZone',
    'IntlBreakIterator',
    'IntlRuleBasedBreakIterator',
    'IntlCodePointBreakIterator',
  ]),
]);
